version: 2
updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: master
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: gradle
    labels: []
    directory: /
    target-branch: master
    schedule:
      interval: monthly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
