apply plugin: 'com.android.application'

def appVersionName = project.findProperty("versionName") ?: "7.0.0"
def appVersionCode = project.findProperty("versionCode") ? project.property("versionCode").toInteger() : 70000

android {
    defaultConfig {
        applicationId "rkr.simplekeyboard.inputmethod"
        compileSdk 37
        minSdkVersion 24
        targetSdkVersion 37
        versionCode appVersionCode
        versionName appVersionName
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    buildFeatures {
        buildConfig = true
    }
    namespace 'rkr.simplekeyboard.inputmethod'
}

dependencies {
    implementation 'androidx.annotation:annotation:1.8.0'
    implementation 'androidx.autofill:autofill:1.3.0'
    testImplementation 'junit:junit:4.13.2'
}
